### ISSUE TITLE
How to use the library to convert wav to opus

### ISSUE THREAD

**Issue by mbrt** [grishka/libtgvoip#23]
This is more a question than an issue, but since I don't see any documentation I'm gonna ask here. Is it possible, and if so how, to use this library to convert PCM audio coming from a file to opus? This seems the only library able to output opus files that Telegram likes on all platforms. I tried without success by using `ffmpeg`, `opusenc` and `oggenc`.

**Comment by grishka** [comment]
This library doesn't output any ogg opus files, it streams raw opus-encoded data using its own protocol. You're looking for [this](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/jni/audio.c).
