### ISSUE TITLE
make pulseaudio dependency optional

### ISSUE THREAD

**Issue by Francesco149** [grishka/libtgvoip#26]
I was tweaking telegram desktop to compile on a musl-libc based distro with no pulseaudio and I noticed that your library unconditionally pulls in pulse, which was making it impossible to build it.

Since you also implement ALSA output, why not make pulse optional?

I'm not really familiar with gyp builds so I really can't help with integrating it into the build system, but at the moment I'm using this patch https://gist.github.com/Francesco149/9232b755f06bd45662d44a8b4cb0cf64 and adding ```-DLIBTGVOIP_WITHOUT_PULSE``` and it works fine, although it's not the nicest thing ever.

**Comment by grishka** [comment]
It only requires the headers and only during build. Libpulse itself is always loaded dynamically, and ALSA is used if it failed to load.

**Comment by Francesco149** [comment]
oh, I did not catch the dynamic loading at all, my bad. mhm, okay sounds good enough since I can just unpack a tarball of pulse's headers at build time. thanks for the info!
