### ISSUE TITLE
Build failure against OpenSSL 1.1.0

### ISSUE THREAD

**Issue by xuzhao9** [grishka/libtgvoip#37]
Starting from OpenSSL 1.1.0, the AES_ctr128_encrypt function called in VoIPController.cpp file is removed. Changing the function to AES_cfg128_encrypt and coercively converting the argument type can fix the compilation error, but it may not work in practice.

**Comment by mymedia2** [comment]
Hey, look at my pull request #31.

It appears to break build against old OpenSSL 1.0.1, but I'm going to
fix this issue shortly.

**Comment by Aokromes** [comment]
I wonder if cannot be changed to LibreSSL instead.

**Comment by grishka** [comment]
I've merged #31 yesterday so we can assume this one is resolved as well.
