### ISSUE TITLE
Feature request: Support push-to-talk in voice chat

### ISSUE THREAD

**Issue by audreytoskin** [grishka/libtgvoip#38]
(repost of my original request on https://github.com/telegramdesktop/tdesktop/issues/4175)

It'd be cool if Telegram supported a push-to-talk function for its voice chat: Instead of always transmitting audio, Telegram would only transmit while I'm holding a (configurable) key on my keyboard, and/or a button on the interface. Ideally, the key would still work even if the Telegram client doesn't currently have focus.

Push-to-talk is most commonly associated with voice chat applications geared toward gamers, but I actually find apps like Mumble useful for any sort of voice-chat context, because its push-to-talk feature minimizes any possible background noises or side talk the other person has to listen to.

**Comment by grishka** [comment]
If you want to just toggle your microphone on/off with a keyboard shortcut, it's more appropriate to request that from tdesktop. The library is more low-level than that and doesn't handle any UI or keyboard input directly.

**Comment by audreytoskin** [comment]
That's what I would have thought, but @stek29 [said to repost here](https://github.com/telegramdesktop/tdesktop/issues/4175#issuecomment-351294707).

**Comment by stek29** [comment]
Lol I haven't thought about turning microphone on and off, sorry :\
