### ISSUE TITLE
missing in source code

### ISSUE THREAD

**Issue by emjeykm** [grishka/libtgvoip#4]
why this library missing in source code??

**Comment by stek29** [comment]
@mojerad Please don't open duplicate issues.

**Comment by emjeykm** [comment]
@stek29 sorry i have issue tell me how can use this library

**Comment by danog** [comment]
Well you just DO IT as in READ THE SOURCE CODE and UNDERSTAND THE SOURCE CODE and IMPLEMENT A WRAPPER like I'm doing :DDD
