### ISSUE TITLE
Building under Linux from CLI development tools

### ISSUE THREAD

**Issue by kvishnivetsky** [grishka/libtgvoip#43]
Hi!
Is it possible to build this library from a CLI Make/CMake under Linux?
I did not find any Makefile in project root.

**Comment by Infactum** [comment]
See [GYP](https://raw.githubusercontent.com/telegramdesktop/tdesktop/55e56a6788870e6d67d9938eaabdf87f2ebddb17/Telegram/gyp/Telegram.gyp) file for build details.
I think there is no seperate makefile cause library is a bit useless by itself, when not beeing a part of bigger project.

**Comment by grishka** [comment]
I do have plans to write a proper makefile for it sometime in the future.

**Comment by grishka** [comment]
@Infactum it turns out the Linux community doesn't think so since it is now available in many different package repos and it apparently builds as a shared library. I have no idea how would one use it without a Telegram client though.

**Comment by kvishnivetsky** [comment]
And it will be very well if there will be several separate componnents:
1. p2p protocol
2. Codec
3. Integral MediaTerminal, which includes item 1,2 and Sound Devices interraction.
I think, this will be an optional dev project structure.

**Comment by grishka** [comment]
Well for the codec I'd just say that it depends on libopus and that's it. That's already the way the package managers handle it. Maybe I'll also add audio I/O using a local socket for some advanced, bot-like usage, enabled through a define.

**Comment by danog** [comment]
That's what my wrapper can do using simple single FIFOs to write audio frames: https://github.com/danog/php-libtgvoip
I could help adapting my code to include a simple CLI API, but you can also use the PHP API it already provides.

**Comment by berkus** [comment]
Automake, srsly, which year is this?
