### ISSUE TITLE
Don't work handle of changing default audio device for VoIP in Windows.

### ISSUE THREAD

**Issue by aleus** [grishka/libtgvoip#45]
### Steps to reproduce in Telegram Desktop
1. Change audio device from default;
2. Call somebody and talk.

### Expected behaviour
VoIP must to use default audio device.

### Actual behaviour
VoIP use last installed audio device always. O

### Configuration
**Operating system:**
Windows 10 x64

**Audio Devices:**
asus xonar essence stx
m.stage HPA-3U⁺

**Version of Telegram Desktop:**
1.2.17

**Comment by grishka** [comment]
Could you please post a screenshot of the audio settings window after you change the default device?

**Comment by aleus** [comment]
Which settings? Telegram doesn't have audio settings.

**Comment by grishka** [comment]
The system settings window where you've changed the audio device.

**Comment by aleus** [comment]
![image](https://user-images.githubusercontent.com/1224122/40778299-638a40fe-64d9-11e8-967c-2f57c3c6b797.png)

**Comment by grishka** [comment]
This way you're changing the default playback device, but VoIP uses the default communication device. Right click on the speaker icon in the tray to access the extended settings and change the default communication device.

**Comment by aleus** [comment]
This? 
![image](https://user-images.githubusercontent.com/1224122/40778514-14153b72-64da-11e8-840a-925ca6125eb1.png)
Or this?
![image](https://user-images.githubusercontent.com/1224122/40778524-1e8d6da4-64da-11e8-83e1-4b51a8028beb.png)

**Comment by grishka** [comment]
On the playback tab you can right click devices to set them as either kind of default. Same goes for recording.

**Comment by aleus** [comment]
![image](https://user-images.githubusercontent.com/1224122/40779006-046e07b0-64dc-11e8-8303-f614047aff93.png)
I didn't know about it before. Thanks. It's work: feature, not bug. :)
