### ISSUE TITLE
sources for static libraries

### ISSUE THREAD

**Issue by thermatk** [grishka/libtgvoip#5]
Hello!
The [Telegram-FOSS project](https://github.com/slp/Telegram-FOSS), the FOSS friendly fork of the Android app available on F-Droid, needs the sources for the included static libraries, as it can't be using the prebuilts.
In the issue https://github.com/grishka/libtgvoip/issues/1 you have showed intention to release those sources, could you please do it now, since the version with call support is already in production?
Thank you in advance!

**Comment by stek29** [comment]
@thermatk Latest released version of libtgvoip is 0.3.2, and production has 0.3.2 too. 
What libraries are you talking about?

UPD: Oh, libwebrtcaec...

**Comment by thermatk** [comment]
@stek29 the sources for building the libWebRtcAec libraries https://github.com/grishka/libtgvoip/tree/public/external , am I just missing their location?

**Comment by grishka** [comment]
I will publish the sources this week.

**Comment by thermatk** [comment]
@grishka thank you! Eagerly waiting =)

**Comment by grishka** [comment]
Apply the attached patch to the Android app to make use of the sources.

[Android.mk.diff.zip](https://github.com/grishka/libtgvoip/files/908376/Android.mk.diff.zip)
