### ISSUE TITLE
AudioIO.h is missing

### ISSUE THREAD

**Issue by applke** [grishka/libtgvoip#54]
Hi, can u hell me? When i try to make, seems like my Ubuntu can't find AudoIO.h file

**Comment by Infactum** [comment]
Try to change this line https://github.com/grishka/libtgvoip/blob/8d8522a5e89f8bb44119d4d35f94a3f18d61f115/audio/AudioIOCallback.h#L10 to `#include "AudioIO.h"`

**Comment by applke** [comment]
Thanks a lot! I want to use this lib on windows and with Java. Can u help me to compile this lib on ubuntu for windows?
