### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by Fgabz** [grishka/libtgvoip#6]
Hey guys quick question, 

Is it possible to integrate the lib like other VOIP lib like PJSIP. Do you think to add a wiki or a Readme to explain how to use the lib on Android ?

**Comment by grishka** [comment]
I may add some brief docs in the future. In the meantime, there's always the Android Telegram app source that you can check out and see how it's used.

**Comment by Fgabz** [comment]
OK cool, I will check that out. Thanks !
