### ISSUE TITLE
if defined(WEBRTC_ARCH_ARM_FAMILY) && defined(WEBRTC_ARCH_X86_FAMILY)

### ISSUE THREAD

**Issue by vitlav** [grishka/libtgvoip#60]
diff --git a/webrtc_dsp/modules/audio_processing/aec3/adaptive_fir_filter.cc b/webrtc_dsp/modules/audio_processing/aec3/adaptive_fir_filter.cc
index 7449fdc..727b74a 100644
--- a/webrtc_dsp/modules/audio_processing/aec3/adaptive_fir_filter.cc
+++ b/webrtc_dsp/modules/audio_processing/aec3/adaptive_fir_filter.cc
@@ -353,7 +353,7 @@ void ApplyFilter_NEON(const RenderBuffer& render_buffer,
 }
 #endif
 
-#if defined(WEBRTC_ARCH_ARM_FAMILY) && defined(WEBRTC_ARCH_X86_FAMILY)
+#if defined(WEBRTC_ARCH_ARM_FAMILY) || defined(WEBRTC_ARCH_X86_FAMILY)

**Comment by grishka** [comment]
Weird, should probably be just

#if defined(WEBRTC_ARCH_X86_FAMILY)

since it's SSE2 code that's wrapped in there. I was copy-pasting too much
