### ISSUE TITLE
Provide a readme.

### ISSUE THREAD

**Issue by mostafa8026** [grishka/libtgvoip#64]
Could you please provide a readme about what is it? I just came across this GitHub and I really wanna know what is the relationship between VoIP and telegram. 
I read this issue #6 and providing a readme file make it better to understand your git.
Thanks.

**Comment by grishka** [comment]
VoIP is any kind of voice calls carried over an IP network, it doesn't necessarily imply interconnecting with traditional phone lines. This library implements Telegram calls.

**Comment by Vincymic** [comment]
When will you also enter video calls on telegram? Or at least group calls ....

**Comment by frzifus** [comment]
oh yes I'm waiting for videocalls too.

**Comment by grishka** [comment]
This isn't the right place for such discussions.

**Comment by Vincymic** [comment]
and what would be the right place? :)

**Comment by grishka** [comment]
/dev/null probably

**Comment by Vincymic** [comment]
why did you add the "video" folder about two months ago? Surely you are working on video calls otherwise it would not make sense ...
