### ISSUE TITLE
Audio callbacks are compiled in by default

### ISSUE THREAD

**Issue by zevlg** [grishka/libtgvoip#68]
I've noticed that audio callbacks compiles in even if `--enable-audio-callback` is not specified.  Might be a typo error for action-if-not-given in configure.ac.  I use next patch:

```c
index f5f5dc0..c21f162 100644
--- a/configure.ac
+++ b/configure.ac
@@ -44,7 +44,7 @@ AS_CASE([$host_os],
 )
 AM_CONDITIONAL(TARGET_OS_OSX, test "x$os_osx" == xyes)
 
-AC_ARG_ENABLE([audio-callback], [AS_HELP_STRING([--enable-audio-callback], [enable callback-based audio I/O])], [], [enable_audio_callback=yes])
+AC_ARG_ENABLE([audio-callback], [AS_HELP_STRING([--enable-audio-callback], [enable callback-based audio I/O])], [], [enable_audio_callback=no])
 AM_CONDITIONAL(ENABLE_AUDIO_CALLBACK, test "x$enable_audio_callback" == xyes)
 
 AS_IF([test "x$os_osx" != xyes && test "x$enable_audio_callback" != xyes], [ # Linux
```

Enabling audio callbacks by default gives a problem, program that uses libtgvoip must also define `TGVOIP_USE_CALLBACK_AUDIO_IO`, because this macro is used to define VoIPController class members.  I've got multiple random crashes before figured out that TGVOIP_USE_CALLBACK_AUDIO_IO was defined on libtgvoip compilation.

**Comment by zevlg** [comment]
Any chances to get this in master?

Or maybe rename help string to "--disable-audio-callback" (as for dsp feature), so user will get the idea that callbacks are compiled in by default?

**Comment by grishka** [comment]
Could you please make it a pull request?
