### ISSUE TITLE
Is Server Needed ?

### ISSUE THREAD

**Issue by Elqul** [grishka/libtgvoip#7]
Hello ,

does this lib need a server to start making and receiving calls ? if yes what type of server is required ?

**Comment by grishka** [comment]
It isn't designed to work on its own at all. It's supposed to be built into Telegram clients, and it requires a Telegram server for key exchange and another one for UDP relay. One can, in theory, run the key exchange part any way they want (assuming the process yields a 256-byte array) and make a compatible relay server, but... why?
