### ISSUE TITLE
Failed to build (windows), "no rule to make target"

### ISSUE THREAD

**Issue by zarEclEC** [grishka/libtgvoip#71]
```
process_begin: CreateProcess(NULL, "", ...) failed.
make: *** No rule to make target `C:/git/bettergram-android/TMessagesProj/jni/./libtgvoip/webrtc_dsp/webrtc/common_audio/ring_buffer.c', needed by `C:/git/bettergram-android/TMessagesProj/build/intermediates/ndkBuild/afat/debug/obj/local/armeabi-v7a/objs-debug/voip/./libtgvoip/webrtc_dsp/webrtc/common_audio/ring_buffer.o'.  Stop.
```

Full log here
https://gist.github.com/ArmeF97/66a13c1ff0f83229f6f30990da4de81d
direct link https://gist.githubusercontent.com/ArmeF97/66a13c1ff0f83229f6f30990da4de81d/raw/f5794e4640052c8e2260c3a4d095b95f36884769/Build%2520failed%2520libtgvoip

**Comment by grishka** [comment]
For now, you're supposed to use the same commit the client repository has as its submodule.

**Comment by zarEclEC** [comment]
Ok, thanks
