### ISSUE TITLE
Missing tag for latest commit

### ISSUE THREAD

**Issue by xvitaly** [grishka/libtgvoip#78]
Latest Telegram Desktop points to commit 7b62334d2f32c44f0b19aff5278e7eb85b28b02c. Can you create a new Git tag with it?

**Comment by xvitaly** [comment]
@grishka Telegram Desktop stable was released. Please create a new version tag.

**Comment by grishka** [comment]
Why do you keep needing these pesky tags, this doesn't fit into my workflow

**Comment by zamazan4ik** [comment]
Because it's a good practice in software development? E.g. some other integrations can rely on git tags.

**Comment by andy-shev** [comment]
> Why do you keep needing these pesky tags, this doesn't fit into my workflow

It's not about your workflow, it's about standard de facto in the industry how software does releases. I would recommend to reconsider.
