### ISSUE TITLE
how can i use voipgroup call？

### ISSUE THREAD

**Issue by honglei92** [grishka/libtgvoip#86]
how can i use voipgroup call？

**Comment by grishka** [comment]
It requires backend API that's not in production and lots of client-side code. You can't.

**Comment by honglei92** [comment]
can i use two voip call to complete the three people voipCall，now our backend api can one to one。

**Comment by grishka** [comment]
You can do whatever you want

**Comment by honglei92** [comment]
but the single voipcall not support three people，can you give me some idea ，tks
