### ISSUE TITLE
TGVOIP_ERROR_AUDIO_IO

### ISSUE THREAD

**Issue by temx** [grishka/libtgvoip#9]
I don't know if this is the right place for this but I'm getting an "Error initializing audio hardware" error in an LG-E610 running Android 4.1.2 which apparently maps to the constant above.

It's the first time I see an error of that kind on this terminal, in particular Telegram's audio messages work fine, and so do other telephony apps (the ones starting with Sk and Wh at least).

I can test custom APKs if needed, but only for a week or so since the phone is not mine.

**Comment by grishka** [comment]
This has already been fixed a while ago. The issue was in the Java part which is in the main Android app repository. You'll have to wait for the dev to update the sources.

**Comment by temx** [comment]
Indeed, this seems to be working in 4.0, thanks.
